server:
  port: 8001

spring:
  application:
    name: could-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/paymentdb?useUnicode=true&characterEncoding=utf-8&useDDL=false
    username: root
    password: 314159mySQL
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yang.springcloud.entities