server:
  port: 8002

spring:
  application:
    name: could-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/paymentdb?useUnicode=true&characterEncoding=utf-8&useDDL=false
    username: root
    password: 314159mySQL

  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yang.springcloud.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #集群版

  instance:
    instance-id: payment8002
    prefer-ip-address: true